spring.application.name=IngestionService

server.port=8081

server.tomcat.connection-timeout=300000
server.tomcat.max-connections=200
server.tomcat.threads.max=50
server.tomcat.threads.min-spare=10

spring.kafka.bootstrap-servers=localhost:9092,localhost:9093,localhost:9094

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

file.upload-dir=./uploads

spring.servlet.multipart.max-file-size=2048MB
spring.servlet.multipart.max-request-size=2048MB
spring.servlet.multipart.file-size-threshold=1MB

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

logging.level.com.vulnuris=INFO
logging.level.org.springframework.kafka=WARN